#!/bin/bash
#SBATCH --job-name="COLEMANTEST"
#SBATCH --output="COLEMANTEST.%j.%N.out"
#SBATCH --partition=week-long-cpu
#SBATCH --nodes=1
#SBATCH --nodelist=node[44]
#SBATCH --ntasks-per-node=36
#SBATCH --export=ALL
#SBATCH -t 96:00:00

mpirun sprayFoam -parallel
