#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# Reconstruct the Decomposed Mesh
runApplication reconstructPar

# Convert Foam Output to VTK format
runApplication foamToVTK
#------------------------------------------------------------------------------
